### ISSUE TITLE
CLI version

### ISSUE THREAD

**Issue by minhhut** [CastagnaIT/NFAuthenticationKey#3]
First of all, thanks for great add-on, it helps to watch Netflix with my Linux PC ;). But I could not login with user/pass, then I tried with NFAuthenticationKey but i find it doesn't work if I don't have Chrome browser. Then I decided to create CLI version which I find it works on all platforms and doesn't require to play with browser to get cookies. Here is mine version: https://github.com/minhhut/NFAuthenticationKeyCli

**Comment by CastagnaIT** [comment]
Hi
thanks for the report

but i can not approve your solution

your solution allows users to steal other people accounts in a easy way
and it relies on third-party external plugins that manipulate cookies with no guarantee of reliability

The basic principles of my scripts is to try to do the operations as secure as possible despite the limitations,
by limiting the use of external software/scripts/plugin/etc...
this does not exclude the more experienced users from doing malpractice, but the majority of amateur/novice users are discouraged/not able to do it

simplifying things must not compromise the security
you could more easily have consequences from the Netflix company
because you are putting the entire community at risk
